version: "3"
services:
  frontend:
    image: "nginx:latest"
    ports:
      - "8088:80"
    volumes:
      - /home/alex/devops-mentor-docker-task19/src/html:/usr/share/nginx/html:ro
      - nginx-data:/var/log/nginx
    networks:
      - front_back_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18
    environment:
      ENV_NAME: staging
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "0.25"
          memory: 50M
    networks:
      - front_back_net

volumes:
  nginx-data:

networks:
  front_back_net:
