version: "3"
services:
  frontend:
    image: "nginx:latest"
    ports:
      - "8088:80"
    volumes:
      - /home/alex/devops-mentor-docker-task19/src/html:/usr/share/nginx/html:ro
      - nginx-data:/var/log/nginx
    networks:
      - front_back_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18
    environment:
      ENV_NAME: staging
    networks:
      - front_back_net

volumes:
  nginx-data:

networks:
  front_back_net:
